name: Deploy to Github Pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to Github Pages
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '12'
        - name: Install packages
          run: npm i
        - name: Set Creds
          run: git config user.name "deploy_bot" && git config user.email "soddyque@gmail.com"
        - name: Build
          run: npm run build
        - name: Deploy
          run: |
            git checkout --orphan gh-pages
            git --work-tree dist add --all
            git --work-tree commit -m "gh-pages"
            git push origin HEAD:gh-pages --force
            rm -r dist
            git checkout -f master
            git branch -D gh-pages
